language: node_js

node_js:
  - '12'
  - '10'
  - '8'

before_install:
  - node --version
  - yarn --version

install:
  - npm install

os:
  - linux
  - osx
  - windows

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - os: windows

script:
  - npm test
